# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CompressDotBim

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DotBimBufferRotation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DotBimBufferRotation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDotBimBufferRotation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DotBimBufferRotation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DotBimBufferRotation
    def Qx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DotBimBufferRotation
    def Qy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DotBimBufferRotation
    def Qz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DotBimBufferRotation
    def Qw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def DotBimBufferRotationStart(builder):
    builder.StartObject(4)

def Start(builder):
    DotBimBufferRotationStart(builder)

def DotBimBufferRotationAddQx(builder, qx):
    builder.PrependFloat32Slot(0, qx, 0.0)

def AddQx(builder, qx):
    DotBimBufferRotationAddQx(builder, qx)

def DotBimBufferRotationAddQy(builder, qy):
    builder.PrependFloat32Slot(1, qy, 0.0)

def AddQy(builder, qy):
    DotBimBufferRotationAddQy(builder, qy)

def DotBimBufferRotationAddQz(builder, qz):
    builder.PrependFloat32Slot(2, qz, 0.0)

def AddQz(builder, qz):
    DotBimBufferRotationAddQz(builder, qz)

def DotBimBufferRotationAddQw(builder, qw):
    builder.PrependFloat32Slot(3, qw, 0.0)

def AddQw(builder, qw):
    DotBimBufferRotationAddQw(builder, qw)

def DotBimBufferRotationEnd(builder):
    return builder.EndObject()

def End(builder):
    return DotBimBufferRotationEnd(builder)
