// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DotBimBufferVector {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DotBimBufferVector {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDotBimBufferVector(bb:flatbuffers.ByteBuffer, obj?:DotBimBufferVector):DotBimBufferVector {
  return (obj || new DotBimBufferVector()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDotBimBufferVector(bb:flatbuffers.ByteBuffer, obj?:DotBimBufferVector):DotBimBufferVector {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DotBimBufferVector()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

z():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startDotBimBufferVector(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldInt32(0, x, 0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldInt32(1, y, 0);
}

static addZ(builder:flatbuffers.Builder, z:number) {
  builder.addFieldInt32(2, z, 0);
}

static endDotBimBufferVector(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDotBimBufferVector(builder:flatbuffers.Builder, x:number, y:number, z:number):flatbuffers.Offset {
  DotBimBufferVector.startDotBimBufferVector(builder);
  DotBimBufferVector.addX(builder, x);
  DotBimBufferVector.addY(builder, y);
  DotBimBufferVector.addZ(builder, z);
  return DotBimBufferVector.endDotBimBufferVector(builder);
}
}
